APPLY_FIXES: all
DEFAULT_BRANCH: main
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FORMATTERS_DISABLE_ERRORS: false
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
JSON_PRETTIER_FILE_EXTENSIONS:
  - .json
  - .md
JSON_ESLINT_PLUGIN_JSONC_PRE_COMMANDS:
  # See https://github.com/nvuillam/mega-linter/issues/773.
  - command: npm install eslint-plugin-jsonc@1.7.0
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
