APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DEFAULT_BRANCH: main
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK # Superseded by Lychee
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
CREDENTIALS_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
JSON_PRETTIER_FILE_EXTENSIONS:
  - .json
  - .md
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
