name: Notify Assignee
on:
  pull_request:
    types:
      - assigned
jobs:
  notify-assignee:
    runs-on: ubuntu-20.04
    steps:
      - name: Send Slack notification assigning pull request.
        uses: ScribeMD/slack-templates@0.2.3
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ASSIGN_CHANNEL_ID }}
          template: assignee
