name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write # for pre-commit-action
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository.
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Use Docker in rootless mode.
        uses: ./
      - name: Run pre-commit hooks.
        uses: ScribeMD/pre-commit-action@aaa96559a813c7280f69aa91a73916dc3eabf19e # 0.9.116
      - name: Send Slack notification with job status.
        if: always()
        uses: ScribeMD/slack-templates@bea126c3915616204196f29d27d6ab9526d61a25 # 0.6.37
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
          template: result
