name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository.
        uses: actions/checkout@v3.0.2
      - name: Install asdf-managed tools based on .tool-versions.
        uses: asdf-vm/actions/install@v1.1.0
        with:
          asdf_branch: v0.10.0
      - name: Add Poetry and its dependencies to PATH.
        run: |
          for version in ~/.asdf/installs/poetry/*; do
            echo "$version/bin" >> "$GITHUB_PATH"
          done
          echo "${{ github.workspace }}"/.venv/bin >> "$GITHUB_PATH"
      - name: Cache Poetry dependencies.
        uses: actions/cache@v3.0.2
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry dependencies.
        run: poetry install
      - name: Use Docker in rootless mode.
        uses: ./
      - name: Run pre-push hooks.
        uses: pre-commit/action@v2.0.3
        env:
          SKIP: no-commit-to-branch
        with:
          extra_args: "--all-files --hook-stage push"
      - name: Send Slack notification with job status.
        if: always()
        uses: ScribeMD/slack-templates@0.2.3
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
          template: result
