name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write # for pre-commit-action
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository.
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
      - name: Use Docker in rootless mode.
        uses: ./
      - name: Run pre-commit hooks.
        uses: ScribeMD/pre-commit-action@0.9.86
      - name: Send Slack notification with job status.
        if: always()
        uses: ScribeMD/slack-templates@0.6.30
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
          template: result
